#pragma once

/* Generated with cbindgen:0.24.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace ha {
namespace param_tool_box_rs {

struct Percent;

extern "C" {

float to_physical(float normalized, Percent *percent);

} // extern "C"

} // namespace param_tool_box_rs
} // namespace ha
